import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Vercel Website</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ padding: '20px', textAlign: 'center' }}>
        <h1>Welcome to My Vercel Website</h1>
        <p>
          This is a basic demo website built with Next.js and deployed on Vercel.
        </p>
        <p>
          Start by editing <code>pages/index.js</code> to create your own website!
        </p>
      </main>

      <footer style={{ textAlign: 'center', padding: '10px', marginTop: '20px' }}>
        <p>Powered by Next.js & Vercel</p>
      </footer>
    </div>
  );
}
